SiparisYonetimSistemi/Controllers/KullaniciController.cs
using SiparisYonetimSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisYonetimSistemi.Controllers
{
    public class KullaniciController : Controller
    {
        // GET: Kullanici
        public ActionResult Index()
        {
            return View(Veritabani.KullaniciListesi);
        }

        public ActionResult Kaydet()
        {
            return View(new Models.Kullanici());
        }

        [HttpPost]
        public ActionResult Kaydet(Models.Kullanici kullanici)
        {
            Veritabani.KullaniciListesi.Add(kullanici);
            return RedirectToAction("Index");
        }
    }
}

SiparisYonetimSistemi/Controllers/MusteriController.cs
using SiparisYonetimSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisYonetimSistemi.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        public ActionResult Index()
        {
            return View(Veritabani.MusteriListesi);
        }
        
        public ActionResult Kaydet()
        {
            ViewBag.Il = Veritabani.IlGetir();
            ViewBag.Ilce = Veritabani.IlceGetir();
            return View(new Models.Musteri());
        }
        [HttpPost]
        public ActionResult Kaydet(Models.Musteri musteri)
        {
            Veritabani.MusteriListesi.Add(musteri);
            return RedirectToAction("Index");
        }
        public ActionResult Duzenle(int id)
        {
            var musteri = Veritabani.MusteriListesi.Where(x => x.MusteriId == id).SingleOrDefault();
            return View(musteri);
        }
        [HttpPost]
        public ActionResult Duzenle(Models.Musteri musteri)
        {
            var mst = Veritabani.MusteriListesi.Where(x => x.MusteriId == musteri.MusteriId).SingleOrDefault();
            var index = Veritabani.MusteriListesi.IndexOf(mst);
            Veritabani.MusteriListesi[index] = musteri;
            return RedirectToAction("Index");
        }
        public ActionResult Detay(int id)
        {
            var detay = Veritabani.MusteriListesi.Where(x => x.MusteriId == id).FirstOrDefault();
            return View(detay);
        }
        public ActionResult Sil(int id)
        {
            Musteri musteri = Veritabani.MusteriListesi.Where(x => x.MusteriId == id).FirstOrDefault();
            Veritabani.MusteriListesi.Remove(musteri);

            return RedirectToAction("Index");
        }
    }
}

SiparisYonetimSistemi/Controllers/SiparisController.cs
using SiparisYonetimSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisYonetimSistemi.Controllers
{
    public class SiparisController : Controller
    {
        // GET: Siparis
        public ActionResult Index()
        {
            return View(Veritabani.SiparisListesi);
        }
        public ActionResult Kaydet()
        {
            return View(new Models.Siparis()); 
        }
        [HttpPost]
        public ActionResult Kaydet(Models.Siparis siparis)
        {
            Veritabani.SiparisListesi.Add(siparis);
            return RedirectToAction("Index");
        }
        public ActionResult Duzenle(int id)
        {
            var siparis = Veritabani.SiparisListesi.Where(x => x.SiparisId == id).SingleOrDefault();
            return View(siparis);
        }

        [HttpPost]
        public ActionResult Duzenle(Models.Siparis  siparis)
        {
            var stk = Veritabani.SiparisListesi.Where(x => x.SiparisId == siparis.SiparisId).SingleOrDefault();
            var index = Veritabani.SiparisListesi.IndexOf(stk);
            Veritabani.SiparisListesi[index] = siparis;
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            Siparis siparis = Veritabani.SiparisListesi.Where(x => x.SiparisId == id).FirstOrDefault();
            Veritabani.SiparisListesi.Remove(siparis);

            return RedirectToAction("Index");
        }

        public ActionResult Detay(int id)
        {
            var siparis = Veritabani.SiparisListesi.Where(x => x.SiparisId == id).SingleOrDefault();
            return View(siparis);
        }
    }
}

SiparisYonetimSistemi/Controllers/UrunController.cs
using SiparisYonetimSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisYonetimSistemi.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        public ActionResult Index()
        {
            return View(Veritabani.UrunListesi);
        }

        public ActionResult Kaydet()
        {
            return View(new Models.Urun());
        }

        [HttpPost]
        public ActionResult Kaydet(Models.Urun urun)
        {
            Veritabani.UrunListesi.Add(urun);
            return RedirectToAction("Index");
        }

        public ActionResult Duzenle(int id)
        {
            var urun = Veritabani.UrunListesi.Where(x => x.UrunId == id).SingleOrDefault();
            return View(urun);
        }

        [HttpPost]
        public ActionResult Duzenle(Models.Urun urun)
        {
            var stk = Veritabani.UrunListesi.Where(x => x.UrunId == urun.UrunId).SingleOrDefault();
            var index = Veritabani.UrunListesi.IndexOf(stk);
            Veritabani.UrunListesi[index] = urun;
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            Urun urun = Veritabani.UrunListesi.Where(x => x.UrunId == id).FirstOrDefault();
            Veritabani.UrunListesi.Remove(urun); 
       
            return RedirectToAction("Index");
        }

        public ActionResult Detay(int id)
        {
            var urun = Veritabani.UrunListesi.Where(x => x.UrunId == id).SingleOrDefault();
            return View(urun);
        }
    }
}

SiparisYonetimSistemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anasayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ürün", "Index", "Urun")</li>
                    <li>@Html.ActionLink("Müşteri", "Index", "Musteri")</li>
                    <li>@Html.ActionLink("Sipariş", "Index", "Siparis")</li>
                    <li>@Html.ActionLink("Kullanıcı", "Kaydet", "Kullanici")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -ÖZGÜN AY</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>